/**
 * GENERATED FILE — do not edit by hand.
 * Regenerate with: bun scripts/generate-dictionaries.ts
 * (92 scale types; verified by the test suite.)
 */

import { ScaleTypeData } from "./types";

const entries: ScaleTypeData[] = [
  { name: "major pentatonic", aliases: ["pentatonic"], intervals: ["P1","M2","M3","P5","M6"], chroma: 661 },
  { name: "major", aliases: ["ionian"], intervals: ["P1","M2","M3","P4","P5","M6","M7"], chroma: 2741 },
  { name: "minor", aliases: ["aeolian"], intervals: ["P1","M2","m3","P4","P5","m6","m7"], chroma: 1453 },
  { name: "major blues", aliases: [], intervals: ["P1","M2","m3","M3","P5","M6"], chroma: 669 },
  { name: "minor blues", aliases: ["blues"], intervals: ["P1","m3","P4","d5","P5","m7"], chroma: 1257 },
  { name: "melodic minor", aliases: [], intervals: ["P1","M2","m3","P4","P5","M6","M7"], chroma: 2733 },
  { name: "harmonic minor", aliases: [], intervals: ["P1","M2","m3","P4","P5","m6","M7"], chroma: 2477 },
  { name: "bebop", aliases: [], intervals: ["P1","M2","M3","P4","P5","M6","m7","M7"], chroma: 3765 },
  { name: "diminished", aliases: ["whole-half diminished"], intervals: ["P1","M2","m3","P4","d5","m6","M6","M7"], chroma: 2925 },
  { name: "dorian", aliases: [], intervals: ["P1","M2","m3","P4","P5","M6","m7"], chroma: 1709 },
  { name: "lydian", aliases: [], intervals: ["P1","M2","M3","A4","P5","M6","M7"], chroma: 2773 },
  { name: "mixolydian", aliases: ["dominant"], intervals: ["P1","M2","M3","P4","P5","M6","m7"], chroma: 1717 },
  { name: "phrygian", aliases: [], intervals: ["P1","m2","m3","P4","P5","m6","m7"], chroma: 1451 },
  { name: "locrian", aliases: [], intervals: ["P1","m2","m3","P4","d5","m6","m7"], chroma: 1387 },
  { name: "ionian pentatonic", aliases: [], intervals: ["P1","M3","P4","P5","M7"], chroma: 2225 },
  { name: "mixolydian pentatonic", aliases: ["indian"], intervals: ["P1","M3","P4","P5","m7"], chroma: 1201 },
  { name: "ritusen", aliases: [], intervals: ["P1","M2","P4","P5","M6"], chroma: 677 },
  { name: "egyptian", aliases: [], intervals: ["P1","M2","P4","P5","m7"], chroma: 1189 },
  { name: "neapolitan major pentatonic", aliases: [], intervals: ["P1","M3","P4","d5","m7"], chroma: 1137 },
  { name: "vietnamese 1", aliases: [], intervals: ["P1","m3","P4","P5","m6"], chroma: 425 },
  { name: "pelog", aliases: [], intervals: ["P1","m2","m3","P5","m6"], chroma: 395 },
  { name: "kumoijoshi", aliases: [], intervals: ["P1","m2","P4","P5","m6"], chroma: 419 },
  { name: "hirajoshi", aliases: [], intervals: ["P1","M2","m3","P5","m6"], chroma: 397 },
  { name: "iwato", aliases: [], intervals: ["P1","m2","P4","d5","m7"], chroma: 1123 },
  { name: "in-sen", aliases: [], intervals: ["P1","m2","P4","P5","m7"], chroma: 1187 },
  { name: "lydian pentatonic", aliases: ["chinese"], intervals: ["P1","M3","A4","P5","M7"], chroma: 2257 },
  { name: "malkos raga", aliases: [], intervals: ["P1","m3","P4","m6","m7"], chroma: 1321 },
  { name: "locrian pentatonic", aliases: ["minor seven flat five pentatonic"], intervals: ["P1","m3","P4","d5","m7"], chroma: 1129 },
  { name: "minor pentatonic", aliases: ["vietnamese 2"], intervals: ["P1","m3","P4","P5","m7"], chroma: 1193 },
  { name: "minor six pentatonic", aliases: [], intervals: ["P1","m3","P4","P5","M6"], chroma: 681 },
  { name: "flat three pentatonic", aliases: ["kumoi"], intervals: ["P1","M2","m3","P5","M6"], chroma: 653 },
  { name: "flat six pentatonic", aliases: [], intervals: ["P1","M2","M3","P5","m6"], chroma: 405 },
  { name: "scriabin", aliases: [], intervals: ["P1","m2","M3","P5","M6"], chroma: 659 },
  { name: "whole tone pentatonic", aliases: [], intervals: ["P1","M3","d5","m6","m7"], chroma: 1361 },
  { name: "lydian #5p pentatonic", aliases: [], intervals: ["P1","M3","A4","A5","M7"], chroma: 2385 },
  { name: "lydian dominant pentatonic", aliases: [], intervals: ["P1","M3","A4","P5","m7"], chroma: 1233 },
  { name: "minor #7m pentatonic", aliases: [], intervals: ["P1","m3","P4","P5","M7"], chroma: 2217 },
  { name: "super locrian pentatonic", aliases: [], intervals: ["P1","m3","d4","d5","m7"], chroma: 1113 },
  { name: "minor hexatonic", aliases: [], intervals: ["P1","M2","m3","P4","P5","M7"], chroma: 2221 },
  { name: "augmented", aliases: [], intervals: ["P1","A2","M3","P5","A5","M7"], chroma: 2457 },
  { name: "piongio", aliases: [], intervals: ["P1","M2","P4","P5","M6","m7"], chroma: 1701 },
  { name: "prometheus neapolitan", aliases: [], intervals: ["P1","m2","M3","A4","M6","m7"], chroma: 1619 },
  { name: "prometheus", aliases: [], intervals: ["P1","M2","M3","A4","M6","m7"], chroma: 1621 },
  { name: "mystery #1", aliases: [], intervals: ["P1","m2","M3","d5","m6","m7"], chroma: 1363 },
  { name: "six tone symmetric", aliases: [], intervals: ["P1","m2","M3","P4","A5","M6"], chroma: 819 },
  { name: "whole tone", aliases: ["messiaen's mode #1"], intervals: ["P1","M2","M3","A4","A5","A6"], chroma: 1365 },
  { name: "messiaen's mode #5", aliases: [], intervals: ["P1","m2","P4","A4","P5","M7"], chroma: 2275 },
  { name: "locrian major", aliases: ["arabian"], intervals: ["P1","M2","M3","P4","d5","m6","m7"], chroma: 1397 },
  { name: "double harmonic lydian", aliases: [], intervals: ["P1","m2","M3","A4","P5","m6","M7"], chroma: 2515 },
  { name: "altered", aliases: ["super locrian","diminished whole tone","pomeroy"], intervals: ["P1","m2","A2","M3","A4","m6","m7"], chroma: 1371 },
  { name: "locrian #2", aliases: ["half-diminished","aeolian b5"], intervals: ["P1","M2","m3","P4","d5","m6","m7"], chroma: 1389 },
  { name: "mixolydian b6", aliases: ["melodic minor fifth mode","hindu"], intervals: ["P1","M2","M3","P4","P5","m6","m7"], chroma: 1461 },
  { name: "lydian dominant", aliases: ["lydian b7","overtone"], intervals: ["P1","M2","M3","A4","P5","M6","m7"], chroma: 1749 },
  { name: "lydian augmented", aliases: [], intervals: ["P1","M2","M3","A4","A5","M6","M7"], chroma: 2901 },
  { name: "dorian b2", aliases: ["phrygian #6","melodic minor second mode"], intervals: ["P1","m2","m3","P4","P5","M6","m7"], chroma: 1707 },
  { name: "ultralocrian", aliases: ["superlocrian bb7","superlocrian diminished"], intervals: ["P1","m2","m3","d4","d5","m6","d7"], chroma: 859 },
  { name: "locrian 6", aliases: ["locrian natural 6","locrian sharp 6"], intervals: ["P1","m2","m3","P4","d5","M6","m7"], chroma: 1643 },
  { name: "augmented heptatonic", aliases: [], intervals: ["P1","A2","M3","P4","P5","A5","M7"], chroma: 2489 },
  { name: "dorian #4", aliases: ["ukrainian dorian","romanian minor","altered dorian"], intervals: ["P1","M2","m3","A4","P5","M6","m7"], chroma: 1741 },
  { name: "lydian diminished", aliases: [], intervals: ["P1","M2","m3","A4","P5","M6","M7"], chroma: 2765 },
  { name: "leading whole tone", aliases: [], intervals: ["P1","M2","M3","A4","A5","m7","M7"], chroma: 3413 },
  { name: "lydian minor", aliases: [], intervals: ["P1","M2","M3","A4","P5","m6","m7"], chroma: 1493 },
  { name: "phrygian dominant", aliases: ["spanish","phrygian major"], intervals: ["P1","m2","M3","P4","P5","m6","m7"], chroma: 1459 },
  { name: "balinese", aliases: [], intervals: ["P1","m2","m3","P4","P5","m6","M7"], chroma: 2475 },
  { name: "neapolitan major", aliases: [], intervals: ["P1","m2","m3","P4","P5","M6","M7"], chroma: 2731 },
  { name: "harmonic major", aliases: [], intervals: ["P1","M2","M3","P4","P5","m6","M7"], chroma: 2485 },
  { name: "double harmonic major", aliases: ["gypsy"], intervals: ["P1","m2","M3","P4","P5","m6","M7"], chroma: 2483 },
  { name: "hungarian minor", aliases: [], intervals: ["P1","M2","m3","A4","P5","m6","M7"], chroma: 2509 },
  { name: "hungarian major", aliases: [], intervals: ["P1","A2","M3","A4","P5","M6","m7"], chroma: 1753 },
  { name: "oriental", aliases: [], intervals: ["P1","m2","M3","P4","d5","M6","m7"], chroma: 1651 },
  { name: "flamenco", aliases: [], intervals: ["P1","m2","m3","M3","A4","P5","m7"], chroma: 1243 },
  { name: "todi raga", aliases: [], intervals: ["P1","m2","m3","A4","P5","m6","M7"], chroma: 2507 },
  { name: "persian", aliases: [], intervals: ["P1","m2","M3","P4","d5","m6","M7"], chroma: 2419 },
  { name: "enigmatic", aliases: [], intervals: ["P1","m2","M3","d5","m6","m7","M7"], chroma: 3411 },
  { name: "major augmented", aliases: ["major #5","ionian augmented","ionian #5"], intervals: ["P1","M2","M3","P4","A5","M6","M7"], chroma: 2869 },
  { name: "lydian #9", aliases: [], intervals: ["P1","A2","M3","A4","P5","M6","M7"], chroma: 2777 },
  { name: "messiaen's mode #4", aliases: [], intervals: ["P1","m2","M2","P4","A4","P5","m6","M7"], chroma: 2535 },
  { name: "purvi raga", aliases: [], intervals: ["P1","m2","M3","P4","A4","P5","m6","M7"], chroma: 2547 },
  { name: "spanish heptatonic", aliases: [], intervals: ["P1","m2","m3","M3","P4","P5","m6","m7"], chroma: 1467 },
  { name: "bebop minor", aliases: [], intervals: ["P1","M2","m3","M3","P4","P5","M6","m7"], chroma: 1725 },
  { name: "bebop major", aliases: [], intervals: ["P1","M2","M3","P4","P5","A5","M6","M7"], chroma: 2997 },
  { name: "bebop locrian", aliases: [], intervals: ["P1","m2","m3","P4","d5","P5","m6","m7"], chroma: 1515 },
  { name: "minor bebop", aliases: [], intervals: ["P1","M2","m3","P4","P5","m6","m7","M7"], chroma: 3501 },
  { name: "ichikosucho", aliases: [], intervals: ["P1","M2","M3","P4","d5","P5","M6","M7"], chroma: 2805 },
  { name: "minor six diminished", aliases: [], intervals: ["P1","M2","m3","P4","P5","m6","M6","M7"], chroma: 2989 },
  { name: "half-whole diminished", aliases: ["dominant diminished","messiaen's mode #2"], intervals: ["P1","m2","m3","M3","A4","P5","M6","m7"], chroma: 1755 },
  { name: "kafi raga", aliases: [], intervals: ["P1","m3","M3","P4","P5","M6","m7","M7"], chroma: 3769 },
  { name: "messiaen's mode #6", aliases: [], intervals: ["P1","M2","M3","P4","A4","A5","A6","M7"], chroma: 3445 },
  { name: "composite blues", aliases: [], intervals: ["P1","M2","m3","M3","P4","d5","P5","M6","m7"], chroma: 1789 },
  { name: "messiaen's mode #3", aliases: [], intervals: ["P1","M2","m3","M3","A4","P5","m6","m7","M7"], chroma: 3549 },
  { name: "messiaen's mode #7", aliases: [], intervals: ["P1","m2","M2","m3","P4","A4","P5","m6","M6","M7"], chroma: 3055 },
  { name: "chromatic", aliases: [], intervals: ["P1","m2","M2","m3","M3","P4","d5","P5","m6","M6","m7","M7"], chroma: 4095 },
];

// Deep-freeze: the dictionary is shared module state and must be immutable.
for (const entry of entries) {
  Object.freeze(entry.aliases);
  Object.freeze(entry.intervals);
  Object.freeze(entry);
}

export const SCALE_TYPES: readonly ScaleTypeData[] = Object.freeze(entries);
