import { defineConfig } from "vitepress";

// Deployed to GitHub Pages at https://zachacious.github.io/MusicTheoryJS/
export default defineConfig({
  title: "MusicTheoryJS",
  description:
    "A modern, tree-shakable music theory library with first-class support for non-standard tunings, microtonal music, MIDI, and audio analysis.",
  base: "/MusicTheoryJS/",
  lang: "en-US",
  cleanUrls: true,
  lastUpdated: true,

  // The API reference is generated by TypeDoc into docs/public/api and served
  // as static files, so VitePress should not treat /api/ links as dead.
  ignoreDeadLinks: [/^\/api\//],

  head: [
    ["link", { rel: "icon", type: "image/svg+xml", href: "/MusicTheoryJS/favicon.svg" }],
    ["meta", { name: "theme-color", content: "#8b5cf6" }],
    ["meta", { property: "og:type", content: "website" }],
    ["meta", { property: "og:title", content: "MusicTheoryJS" }],
    [
      "meta",
      {
        property: "og:description",
        content:
          "A modern, immutable, tree-shakable music theory library with first-class microtonal, MIDI, and audio-analysis support.",
      },
    ],
    ["meta", { property: "og:image", content: "/MusicTheoryJS/favicon.svg" }],
    ["meta", { name: "twitter:card", content: "summary" }],
  ],

  themeConfig: {
    logo: "/favicon.svg",

    nav: [
      { text: "Guide", link: "/guide/getting-started" },
      { text: "API Reference", link: "/api/" },
      {
        text: "v3",
        items: [
          {
            text: "Changelog",
            link: "https://github.com/Zachacious/MusicTheoryJS/blob/master/CHANGELOG.md",
          },
          {
            text: "Releasing",
            link: "https://github.com/Zachacious/MusicTheoryJS/blob/master/RELEASING.md",
          },
        ],
      },
    ],

    sidebar: {
      "/guide/": [
        {
          text: "Introduction",
          items: [
            { text: "Getting Started", link: "/guide/getting-started" },
            { text: "Core Concepts", link: "/guide/concepts" },
          ],
        },
        {
          text: "Western Theory",
          items: [
            { text: "Notes", link: "/guide/notes" },
            { text: "Intervals & Transposition", link: "/guide/intervals" },
            { text: "Scales", link: "/guide/scales" },
            { text: "Chords", link: "/guide/chords" },
            { text: "Keys & Harmony", link: "/guide/keys" },
          ],
        },
        {
          text: "Beyond 12-TET",
          items: [
            { text: "Tuning & Microtonal", link: "/guide/tuning" },
          ],
        },
        {
          text: "Analysis & I/O",
          items: [
            { text: "Symbolic Analysis", link: "/guide/analysis" },
            { text: "MIDI Files", link: "/guide/midi" },
            { text: "Audio (DSP)", link: "/guide/audio" },
          ],
        },
        {
          text: "Reference",
          items: [{ text: "Full API Reference", link: "/api/" }],
        },
      ],
    },

    socialLinks: [
      {
        icon: "github",
        link: "https://github.com/Zachacious/MusicTheoryJS",
      },
    ],

    search: { provider: "local" },

    editLink: {
      pattern:
        "https://github.com/Zachacious/MusicTheoryJS/edit/master/docs/:path",
      text: "Edit this page on GitHub",
    },

    footer: {
      message: "Released under the ISC License.",
      copyright: "Copyright © Zach Moore",
    },
  },
});
