/*
Progression.js
*/

import Scale from './Scale';
import Chord from './Chord';

/**
 * Generate Chords from a scale and template
 * <br> The template give to the Progression is an array of integers representing
 * <br> interval between scale degrees. [1, 4, 5] will build triad chords from the 1st, 4th, and 5th scale degrees.
 *
 * @memberof module:MT
 * @example
 * const myProgression = new MT.Progression(MT.Scale.major(MT.Note.a()), [1, 4, 5, 7]);
 * console.log(myProgression.asString);
 * // returns Progression: (Chord: A C#/Db E ) (Chord: D F#/Gb A ) (Chord: E G#/Ab B ) (Chord: G#/Ab C D#/Eb )
 */
class Progression {
    /** @private */
    mScale;

    /** @private */
    mChords;

    /** @private */
    mTemplate;

    /**
     *Creates an instance of Progression.

     * @param {Scale} [pScale=new Scale()] pScale - The scale to build the chords upon
     * @param {Array} [pTemplate=[1, 4, 5]] pTemplate - An array containing the scale degrees from which to generate the chords
     * @memberof Progression
     */
    constructor(pScale = new Scale(), pTemplate = [1, 4, 5]) {
      this.mScale = pScale;
      this.template(pTemplate);
    }

    /**
     * Returns a string containing an array of notes for each chord in the progression
     *
     * @readonly
     * @returns {string}
     */
    get asString() {
      let chords = 'Progression: ';
      this.mChords.forEach((item) => {
        chords += `(${item.asString}) `;
      });
      return chords;
    }

    /**
     * Returns an array of chords generated by the progression
     *
     * @readonly
     * @returns {Chords[]} The array of chords
     */
    get chords() {
      return this.mChords;
    }

    /**
     * (chainable) Sets or returns the scale
     *
     * @chainable
     * @param {Scale} [pScale]
     * @returns {(Scale|Progression)} Returns this object if a value is set or returns the scale
     * @example
     * let myProgression = new Progression();
     * myProgression.scale(Scale.minor()).template([1, 2, 6]);
     */
    scale(pScale) {
      if (!pScale) {
        return this.mScale;
      }

      this.mScale = pScale;

      this.mComputeChords();

      return this;
    }

    /**
     * (chainable) Sets or returns the template
     *
     * @chainable
     * @param {Array} [pTemplate] - An array of numbers denoting the scale degree to create the progression from. Ex: [1, 4, 5]
     * @returns {(Array|Progression)} Returns this object if a value is set or returns the template
     * @example
     * let myProgression = new Progression();
     * myProgression.scale(Scale.minor()).template([1, 2, 6]);
     */
    template(pTemplate) {
      if (!pTemplate) {
        return this.mTemplate;
      }

      this.mTemplate = pTemplate;

      this.mComputeChords();

      return this;
    }


    /**
     * Uses the scale and the template to create the chords of the progression
     *
     * @private
     */
    mComputeChords() {
      this.mChords = [];

      let i = 0;
      const numChords = this.mTemplate.length;
      for (i; i < numChords; i++) {
        this.mChords.push(new Chord(this.mScale.degree(this.mTemplate[i])));
      }
    }


    /**
     * Check equality with another Progression
     *
     * @param {Progression} pProgression
     * @returns {Boolean} True if the given Progression is equal
     */
    equals(pProgression) {
      return (pProgression.scale() === this.mScale
        && pProgression.template() === this.mTemplate);
    }

    /**
     * Creates a copy of this object
     *
     * @returns {Progression}
     */
    copy() {
      return new Progression(this.mScale, this.mTemplate);
    }
}

export default Progression;
